on: 
  push:
    branches:
      - main
#name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
        npm run test

#    - name: server_conf
#   - name: 📂 Sync files
#     uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#      with:
#        node-version: 20
#      server: self-hosted
#      username: oluwadamilare
#      password: test@1234
#      protocol: tcp
#      local-dir: ./build/
